# Generated by Django 4.2 on 2024-02-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.IntegerField(
                default=0, help_text="The number of comments on the post"
            ),
        ),
    ]
