# Generated by Django 4.2 on 2024-03-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('post', '0003_alter_comment_id_alter_like_id_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The content type of the like', limit_choices_to={'model__in': ('post', 'comment')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The id of the object being liked', null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['author', 'content_type', 'object_id'], name='post_like_author__139e9e_idx'),
        ),
    ]
