# Generated by Django 4.2 on 2024-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_like_post_comment_type_like_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="object_id",
            field=models.CharField(
                help_text="The id of the object being liked (in the content_type model)",
                max_length=250,
            ),
        ),
    ]