# Generated by Django 4.2 on 2024-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_like_object_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="like",
            name="post_like_author__139e9e_idx",
        ),
        migrations.RemoveField(
            model_name="like",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="like",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="like",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="like",
            name="type",
        ),
        migrations.AddField(
            model_name="like",
            name="object",
            field=models.URLField(
                default="", help_text="The URL ID of the object being liked"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="like",
            name="author",
            field=models.URLField(help_text="The user URL ID who liked the post"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["author", "object"], name="post_like_author_0ae7c0_idx"
            ),
        ),
    ]
