# Generated by Django 4.2 on 2024-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_like_post_like_author__139e9e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isGithub',
            field=models.BooleanField(default=False, help_text='Is this post from Github?'),
        ),
    ]
