# Generated by Django 4.2 on 2024-03-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0002_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
    ]
