# Generated by Django 4.2 on 2024-04-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0003_remove_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
    ]
