# Generated by Django 4.2 on 2024-03-15 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0002_rename_user_inbox_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxComment",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text="the ID of the comment",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("comment", models.TextField(help_text="The content of the comment")),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "contentType",
                    models.CharField(
                        choices=[
                            ("text/plain", "Plain Text"),
                            ("text/markdown", "Markdown"),
                            ("application/base64", "Base64 Application"),
                            ("image/png;base64", "Base64 PNG Image"),
                            ("image/jpeg;base64", "Base64 JPEG Image"),
                            ("image/gif;base64", "Base64 GIF Image"),
                        ],
                        default="text/plain",
                        help_text="Content type of the comment",
                        max_length=250,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who made the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inbox",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inbox.inboxcomment",
            ),
        ),
    ]
