# Generated by Django 4.2 on 2024-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0003_inboxcomment_alter_inbox_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.URLField(help_text="The user who liked the post")),
                (
                    "object",
                    models.URLField(help_text="The URL of the object being liked"),
                ),
            ],
        ),
    ]
