# Generated by Django 4.2 on 2024-03-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0004_inboxlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbox",
            name="like",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inbox.inboxlike",
            ),
        ),
    ]
