# Generated by Django 4.2 on 2024-03-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0007_followrequest_alter_inbox_follow_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followrequest",
            name="object",
            field=models.URLField(),
        ),
    ]
