# Generated by Django 4.2 on 2024-04-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0010_remove_inboxcomment_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followrequest",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_request_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followrequest",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_request_object",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
