# Generated by Django 4.2 on 2024-03-17 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="follower",
            new_name="actor",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="user",
            new_name="object",
        ),
    ]
