# Generated by Django 4.2 on 2024-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_node", "0002_remotenode_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotenode",
            name="disabled",
            field=models.BooleanField(
                default=False, help_text="whether the remote node is disabled"
            ),
        ),
    ]
