# Generated by Django 4.2 on 2024-03-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_node', '0004_incomingnode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomingNode',
        ),
    ]
