name: Django CI

on:
  push:
    branches: [ "2024" ]
  pull_request:
    branches: [ "2024" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python3 -m pip install --upgrade pip
        python3 -m pip install virtualenv
        python3 -m virtualenv venv --python=python3
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cp .env.example .env
        cd backend
        source venv/bin/activate
        python manage.py test
